export default{
    getHomeData:()=>{
        return{
            data:{
                dataList:[
                    {
                        name:'三星8',
                        todayBuy:20000,
                        mouthBUy:2345,
                        totalBuy:288888
                      },
                      {
                        name:'三星9',
                        todayBuy:20000,
                        mouthBUy:2345,
                        totalBuy:288888
                      },
                      {
                        name:'三星7',
                        todayBuy:20000,
                        mouthBUy:2345,
                        totalBuy:288888
                      },
                      {
                        name:'三星5',
                        todayBuy:20000,
                        mouthBUy:2345,
                        totalBuy:288888
                      },
                ]
            }
        }
    },
    getCountData:()=>{
      return {
        data:{
          dataCount:[
            {
              name:'今日支付订单',
              value:'1234',
              icon:'SuccessFiled',
              color:'#2ec7c9'
            },
            {
              name:'今日收藏订单',
              value:'1234',
              icon:'StarFiled',
              color:'#2ec7c9'
            },
            {
              name:'今日未支付订单',
              value:'1234',
              icon:'GoodsFiled',
              color:'#2ec7c9'
            },
            {
              name:'本月支付订单',
              value:'1234',
              icon:'SuccessFiled',
              color:'#2ec7c9'
            },
            {
              name:'本月收藏订单',
              value:'1234',
              icon:'SuccessFiled',
              color:'#2ec7c9'
            },
            {
              name:'本月收藏订单',
              value:'1234',
              icon:'SuccessFiled',
              color:'#2ec7c9'
            },
          

          ]
        }
      }
    },
    getChartData:()=>{
      return {
        data:{
          orderData:{
            date:['20191001','20191002','20191003','20191004','20191005'],
            dataType:[{
              '苹果':"10000",
              '华为':"3000",
              '小米':"3000",
              '一加':"1800",
              'oppo':"1500",
            },
            {
              '苹果':"10000",
              '华为':"3000",
              '小米':"3000",
              '一加':"1800",
              'oppo':"1500",
            },
            {
              '苹果':"10000",
              '华为':"3000",
              '小米':"3000",
              '一加':"1800",
              'oppo':"1500",
            },
            {
              '苹果':"8000",
              '华为':"4000",
              '小米':"3000",
              '一加':"2800",
              'oppo':"1500",
            },
            {
              '苹果':"8000",
              '华为':"6000",
              '小米':"5000",
              '一加':"4800",
              'oppo':"1500",
            },
          ]

          },
          videoData:[
            {
              name:'苹果',
              value:5000
            },
            {
              name:'华为',
              value:2000
            },
            {
              name:'小米',
              value:3000
            },
            {
              name:'一加',
              value:3000
            },
            {
              name:'oppo',
              value:1200
            },
          ],
          userData:[
            {
              date:'周一',
              new:10,
              active:300
            },
            {
              date:'周二',
              new:50,
              active:350
            },
            {
              date:'周三',
              new:55,
              active:380
            },
            {
              date:'周四',
              new:65,
              active:390
            },
            {
              date:'周五',
              new:65,
              active:390
            },
            {
              date:'周六',
              new:75,
              active:410
            },
            {
              date:'周日',
              new:80,
              active:450
            },
          ]
        }
      }
    }
}